from django.db import models

# Create your models here.
class InsuranceClaim(models.Model):
    claim_no = models.CharField(max_length = 10)
    employee_no = models.CharField(max_length = 10)
    employee_name = models.CharField(max_length = 200, blank = True, null = True)
    date_of_birth = models.CharField(max_length = 10)
    company_name = models.CharField(max_length = 200)
    city = models.CharField(max_length = 200)
    state = models.CharField(max_length = 200,blank = True, null = True)
    country = models.CharField(max_length = 200, blank = True, null = True)
    date_of_reporting = models.CharField(max_length = 10)
    time_of_reporting = models.CharField(max_length = 8)
    date_of_incident = models.CharField(max_length = 10)
    time_of_incident = models.CharField(max_length = 8)
    injury_disease = models.CharField(max_length = 200, blank = True, null = True)
    affected_body_part = models.CharField(max_length = 200, blank = True, null = True)
    medical_assistance_req = models.CharField(max_length = 5, blank = True, null = True)
    claim_amount = models.IntegerField()
    witness_present = models.CharField(max_length = 5, blank = True, null = True)
    test_one = models.TextField(blank = True, null = True)
    test_two = models.TextField(blank = True, null = True)
    test_three = models.TextField(blank = True, null = True)
    test_four = models.TextField(blank = True, null = True)
    test_five = models.TextField(blank = True, null = True)
    test_six = models.TextField(blank = True, null = True)
    test_seven = models.TextField(blank = True, null = True)
    test_eight = models.TextField(blank = True, null = True)
    fraudulent_score = models.IntegerField()
    category = models.CharField(max_length = 50)
    processed = models.CharField(max_length = 5)
    name_of_reported_med_prac = models.CharField(max_length = 200, blank = True, null = True)
    med_prac_address = models.TextField(blank = True, null = True)
    med_prac_number = models.CharField(max_length = 10)
    med_prac_expertise = models.CharField(max_length = 200, blank = True, null = True)
    inspector_comments = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.claim_no + ' ' + str(self.claim_amount)