# Generated by Django 3.0.6 on 2020-05-31 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceClaim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_no', models.CharField(max_length=10)),
                ('employee_no', models.CharField(max_length=10)),
                ('employee_name', models.CharField(max_length=200)),
                ('date_of_birth', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('date_of_reporting', models.CharField(max_length=10)),
                ('time_of_reporting', models.CharField(max_length=8)),
                ('date_of_incident', models.CharField(max_length=10)),
                ('time_of_incident', models.CharField(max_length=8)),
                ('injury_disease', models.CharField(max_length=200)),
                ('affected_body_part', models.CharField(max_length=200)),
                ('medical_assistance_req', models.CharField(max_length=5)),
                ('claim_amount', models.IntegerField()),
                ('witness_present', models.CharField(max_length=5)),
                ('test_one', models.TextField()),
                ('test_two', models.TextField()),
                ('test_three', models.TextField()),
                ('test_four', models.TextField()),
                ('test_five', models.TextField()),
                ('fraudulent_score', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('processed', models.CharField(max_length=5)),
                ('name_of_reported_med_prac', models.CharField(max_length=200)),
                ('med_prac_address', models.TextField()),
                ('med_prac_number', models.CharField(max_length=10)),
                ('med_prac_expertise', models.CharField(max_length=200)),
                ('inspector_comments', models.TextField()),
            ],
        ),
    ]
