# Generated by Django 3.0.6 on 2020-06-03 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insuranceclaim',
            name='test_eight',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='test_seven',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insuranceclaim',
            name='test_six',
            field=models.TextField(default='Default'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insuranceclaim',
            name='inspector_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
